# Generated by Django 3.2.8 on 2021-10-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='organisation.organisation'),
        ),
    ]
