# Generated by Django 3.2.8 on 2021-11-03 13:41

from django.db import migrations, models
import organisation.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_member_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[organisation.models.validate_phone_no]),
        ),
    ]
