# Generated by Django 3.2.8 on 2021-11-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20211112_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organisation.organisation'),
        ),
    ]
