# Generated by Django 3.2.8 on 2021-11-03 13:41

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0007_alter_organisation_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo_pic', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_groups', models.BooleanField()),
                ('website', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('O', 'Online'), ('F', 'Offline'), ('H', 'Hybrid')], max_length=1)),
                ('location', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=10, validators=[event.models.validate_phone_no])),
                ('reg_close_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='organisation.organisation')),
            ],
        ),
    ]
