# Generated by Django 3.2.8 on 2021-11-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timezone',
        ),
    ]
