# Generated by Django 3.2.8 on 2021-10-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211029_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
