# Generated by Django 3.2.8 on 2021-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_oauth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
